### ISSUE TITLE
remove slide dynamically

### ISSUE THREAD

**Issue by burhan001** [ZouYouShun/ngx-hm-carousel#11]
Hi, how i can remove slide dynamically.
Thanks in advance

**Comment by ZouYouShun** [comment]
Hi @burhan001 , is your mean remove drag animation? 

https://stackblitz.com/edit/ngx-hm-carousel-fade-example

Maybe the second example is what you want.

**Comment by burhan001** [comment]
@ZouYouShun slider need to update when new object insert or remove from the array which is bind with the slider
