### ISSUE TITLE
Disable drag

### ISSUE THREAD

**Issue by JasperFioole21** [ZouYouShun/ngx-hm-carousel#13]
Is it possible to disable the drag event if the carousel contains only one image?

**Comment by ZouYouShun** [comment]
Hi @JasperFioole21 , there is an sample way to do that.

You can set `[notDrag]` on the `ngx-hm-carousel` 
html
```html
<ngx-hm-carousel
  [notDrag]="notDrag"
  [(ngModel)]="index"
...
```
ts
```ts
  get notDrag(){
    return this.avatars.length === 1;
  }
```

https://stackblitz.com/edit/ngx-hm-carousel-disable-drag

**Comment by JasperFioole21** [comment]
Thank you, works for me!
