### ISSUE TITLE
using with another that images, centent html with arrays

### ISSUE THREAD

**Issue by Paul75** [ZouYouShun/ngx-hm-carousel#15]
Hello,

I want touse your program to slides not image but content html create with the BDD.

I make a service to give datas. I want to call the servie to get result and inset into screen.

But for me it don't works in ngOnInit, for exemple : 
this.dataSource = this.service.getAllLines();

I've got error in console that this.elem[index] undefined....

Thanks

**Comment by ZouYouShun** [comment]
H @Paul75, Could you give your example code, I doesn't know your problem clearly.

You can fork this stackblitz to speed up your work.
https://stackblitz.com/edit/ngx-hm-carousel-disable-drag

**Comment by ZouYouShun** [comment]
hellow @Paul75,  any update?
