### ISSUE TITLE
swipe velocity  

### ISSUE THREAD

**Issue by Rim-777** [ZouYouShun/ngx-hm-carousel#24]
Hello again,
The HammerJs library, which is used under the hood for the ngx-hm-carousel plugin has the specific parameter velocity [](https://hammerjs.github.io/recognizer-swipe/). It is a really  important parameter if the plugin is used in combination with a pan-zoom - functionality or plugin. With correctly customized velocity, HamerJs is able to recognize which move is a swipe.
The question is: Is there a possibility to manage this parameter for the ngx-hm-carousel?  If not, could you please add a swipe-velocity input to the ngx-hm-carousel to have the possibility to manage it?
Thank you in advance 
Timo

**Comment by ZouYouShun** [comment]
Hi @Rim-777 the swipe event isn't binding with carousel currently, need add that event to handle that.

Maybe I can emit the pan element when view ready, that can make developer can binding event by themselves, or some binding `[Input]` with hammer.

What do you think about that ?

**Comment by Rim-777** [comment]
Hi @ZouYouShun, thanks a lot for the quick reaction.
Why Isn't possible to provide additional input to your plugin and add an attribute such as a [swipe-velocity]="some numberer" and then to pass this value to the option 'velocity' like it is described here: https://hammerjs.github.io/recognizer-swipe/  ?
I mean no need to customize the velocity and just pass it next to the HammerJs. Is it possible?

**Comment by Rim-777** [comment]
Hi @ZouYouShun,
Please update me if I've exposed my idea clear enough.  
I just need to understand if updates I've described are possible because if not, I'll have to search for another solution. 
Thank you in advance

**Comment by ZouYouShun** [comment]
Hello @Rim-777, I have updated the new feature with 1.7.0 and support in angular 8.0+, you can try that.

https://ngx-hm-carousel-swipe-velocity.stackblitz.io

Now we can use `[swipe-velocity]` to set the swipe velocity with carousel,

Thanks for your suggestion.

**Comment by Rim-777** [comment]
@ZouYouShun Thank you very much for the update,
Could you please publish the example on https://stackblitz.com ?
For some reason, it doesn't work for me and after I updated the plugin the slide animation stopped working as well.

**Comment by ZouYouShun** [comment]
> @ZouYouShun Thank you very much for the update,
> Could you please publish the example on https://stackblitz.com ?
> For some reason, it doesn't work for me and after I updated the plugin the slide animation stopped working as well.

oh! I pasted the preview link, not editable lint,
https://stackblitz.com/edit/ngx-hm-carousel-swipe-velocity

**Comment by Rim-777** [comment]
@ZouYouShun, thank you for the example.
Unfortunately, it doesn't work as was expected. The idea of the  velocity parameter is the following:
the slide effect shouldn't work if the speed of a swipe is slow. Otherwise when a user tries to zoom and pan a picture the right or left finger-moves will be recognized as a swipe a picture will be replaced. 
Might be there is the possibility to use some parameter such as  [disabled] ='true' to disable the slide during the pan? It, of course, is not perfect but at least it won't replace pictures during the pan.

**Comment by ZouYouShun** [comment]
@Rim-777 I got that because I have a variable to change the picture with user pan distance,

currently, it will change the picture when the user moves more than 15% of the image width.

you can try that at `npm i ngx-hm-carousel@1.7.1`

set `[pan-boundary]="0"`

**Comment by Rim-777** [comment]
@ZouYouShun - I've updated to  "ngx-hm-carousel": "^1.7.1", then tried what you have suggested and got the following error 'Can't bind to 'pan-boundary' since it isn't a known property of 'ngx-hm-carousel'.

**Comment by ZouYouShun** [comment]
> @ZouYouShun - I've updated to "ngx-hm-carousel": "^1.7.1", then tried what you have suggested and got the following error 'Can't bind to 'pan-boundary' since it isn't a known property of 'ngx-hm-carousel'.

oh... I have error typing in the Input field...

**Comment by ZouYouShun** [comment]
> @ZouYouShun - I've updated to "ngx-hm-carousel": "^1.7.1", then tried what you have suggested and got the following error 'Can't bind to 'pan-boundary' since it isn't a known property of 'ngx-hm-carousel'.

Please update again with 1.7.2

set `[pan-boundary]="false"`

**Comment by ZouYouShun** [comment]
@Rim-777 https://stackblitz.com/edit/ngx-hm-carousel-swipe-velocity

**Comment by ZouYouShun** [comment]
Hi @Rim-777, is any issue with that, if not, I will close this issue tonight.

**Comment by Rim-777** [comment]
Hi, unfortunately [pan-boundary]="false" doesn't solve the problem. Even slow swipe pulls along the next picture

**Comment by ZouYouShun** [comment]
Is that example can't display what you want?

I think that is work.

the `pan-boundary` is set the rate of pan distance

and the `swipe-velocity` is set for hammer swipe velocity.

if you want swipe not work with slow speed, you can set `[swipe-velocity]` very small.
