### ISSUE TITLE
mobile - vertical scroll not working

### ISSUE THREAD

**Issue by BayanAbuawadCL** [ZouYouShun/ngx-hm-carousel#25]
When touching the carousel container and trying to scroll vertically it doesn't work and nothing happens.

I am using angular material
angular version is 8.1.1

**Comment by ZouYouShun** [comment]
hi @BayanAbuawadCL, which device you use?

could you provide the device and browser version and type?

**Comment by BayanAbuawadCL** [comment]
Hey @ZouYouShun, you can see it on the browser on device mode try touching the carousel container and scroll vertically you will see that it is not working.

I tested it on Chrome Version 75.0.3770.142 (Official Build) (64-bit).

**Comment by BayanAbuawadCL** [comment]
Solved by removing (swip) event from elements inside the carusel.

using something like :
 `<div>(swipe)="stopCarouselAutoPlay()">......</div> `
inside the carousel kills the vertical scroll.
