### ISSUE TITLE
IE 11 Carousel Loop Issue

### ISSUE THREAD

**Issue by shubhamg2404** [ZouYouShun/ngx-hm-carousel#26]
Hi,
There is a bug in the carousel on internet explorer when the infinite scroll is selected. When all the tiles in carousel are used and it loops to display the first tile the previous tiles disappears which displays empty space and it is not giving feel of infinite looping. PFA image for the example which is presented on documentation when I run it on internet explorer. Is there any possiable fix for this issue?

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/40199840/63696619-bdd3aa00-c838-11e9-840f-ab7c7b6e65bd.png">

Thanks in advance.

**Comment by ZouYouShun** [comment]
Hi @shubhamg2404,

could you provide your template for me, let me can check that on IE.

**Comment by ZouYouShun** [comment]
No response with the creator, close this issue, feel free to reopen that.
