### ISSUE TITLE
Support for Angular 9 SSR.

### ISSUE THREAD

**Issue by kamilogerto2** [ZouYouShun/ngx-hm-carousel#27]
Hey.
Pure hammer js is causing the problems with window reference in the Angular SSR project. To solve that - it's needed to add https://www.npmjs.com/package/@egjs/hammerjs . But since we added that - ngx-hm-carousel is not working. 

It's possible to switch from the hammer js library to egjs/hammerjs in hm-carousel?

Cheers!

**Comment by ZouYouShun** [comment]
Hi @kamilogerto2, not import hammerjs in your SSR environment, you can separate `main.ts` and `main.server.ts` to use that.

**Comment by kamilogerto2** [comment]
Sure. It's an options and I will do that probably. But it would by nice to support that out of the box with egjs ;) There is some reason why you don't want to switch?

**Comment by ZouYouShun** [comment]
thinks we don't have a strong motivation to switch into eggs, I using hammerjs because @angular/material, but that seems can be removed in angular v9.

Maybe I will remove hammerjs in the feature.

thanks for your suggestion.
