### ISSUE TITLE
Is it possible to implement left/right previews of next/previous cards? (check screenshot)

### ISSUE THREAD

**Issue by hazemguent** [ZouYouShun/ngx-hm-carousel#29]
I wanted to know whether it is supported now, by changing some parameters?
or
should I play with CSS to perform something like this? 
If using CSS is possible, can someone give some hints how is it doable?

If not, please try to include it in the next release, thanks in advance :)

![image](https://user-images.githubusercontent.com/53826823/89409005-a4fa9680-d721-11ea-9450-aad5143427c7.png)

**Comment by ZouYouShun** [comment]
Hi @hazemguent, seems in this version the only way to implement that is using a cover div to mask that.

here is an example https://stackblitz.com/edit/ngx-hm-carousel-preview-card
