### ISSUE TITLE
option loop

### ISSUE THREAD

**Issue by kiokotzu** [ZouYouShun/ngx-hm-carousel#3]
It would be great if you have the loop option, so you do not see the jump at the end.

**Comment by shubh4git** [comment]
Do you know how to implement next and previous button in this.

**Comment by ZouYouShun** [comment]
@kiokotzu I will add this option in version1.2.0.
you can set `[infinite]="ture"` to enable it.

Detial look https://alanzouhome.firebaseapp.com/package/NgxHmCarousel
