### ISSUE TITLE
[Question]: Carousel Example for mat-cards with header content and action buttons 

### ISSUE THREAD

**Issue by geyuqiu** [ZouYouShun/ngx-hm-carousel#30]
Hi,

do you happen to have a working carousel Example for mat-cards with header content and action buttons somewhere?
<img width="357" alt="Screenshot 2020-09-02 at 23 57 39" src="https://user-images.githubusercontent.com/4540661/92041432-80252d80-ed78-11ea-9577-aca916e6968f.png">

Appreciate your help.

thx ;)

**Comment by ZouYouShun** [comment]
hi @geyuqiu 

https://stackblitz.com/edit/ngx-hm-carousel-fade-example?file=src%2Fapp%2Fapp.component.html

you can change the content inside `ngx-hm-carousel-container` easily to fit you requirement.
