### ISSUE TITLE
Support for Angular 12

### ISSUE THREAD

**Issue by RoopanV** [ZouYouShun/ngx-hm-carousel#31]
Hi,
    When we try to install the package for angular 12 application facing the below issue.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: fusion@0.0.1
npm ERR! Found: tslib@2.3.0
npm ERR! node_modules/tslib
npm ERR!   tslib@"^2.0.0" from the root project
npm ERR!   tslib@"^2.1.0" from @angular/common@12.0.5
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"~12.0.5" from the root project
npm ERR!     peer @angular/common@">=9.0.0" from ngx-hm-carousel@2.0.0-rc.1
npm ERR!     node_modules/ngx-hm-carousel
npm ERR!       ngx-hm-carousel@"^2.0.0-rc.1" from the root project
npm ERR!   2 more (@angular/core, zone.js)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@"^1.10.0" from ngx-hm-carousel@2.0.0-rc.1
npm ERR! node_modules/ngx-hm-carousel
npm ERR!   ngx-hm-carousel@"^2.0.0-rc.1" from the root project

**Comment by ZouYouShun** [comment]
hi, @RoopanV try to upgrade to v2.0.1, that will be fixed

**Comment by ZouYouShun** [comment]
## 2.0.0

### Feature
- **angular**: update angular to angular 12

### ⚠ BREAKING CHANGES
- **class**: change class name when init component `ngx-hm-carousel-display-npwrap` => `ngx-hm-carousel-display-nowrap`
- **resize-observer-polyfill**: remove dependencies `resize-observer-polyfill`, if you need that polyfill, import that in `polyfills.ts` by your self
- **mouse-enable**: fix error wording `mourse-enable` => `mouse-enable`

**Comment by ZouYouShun** [comment]
there is some breaking change, FYI
