### ISSUE TITLE
Support for Angular 13

### ISSUE THREAD

**Issue by RoopanV** [ZouYouShun/ngx-hm-carousel#32]
Hi,
   Can you please provide support for Angular V13? If I try to run the app facing the below warning:

> ng serve

⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-hm-carousel [es2015/esm2015] (https://github.com/ZouYouShun/ngx-hm-carousel.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by ZouYouShun** [comment]
Hi there! I will try that recently!

**Comment by ZouYouShun** [comment]
upgrade! try to `npm i ngx-hm-carousel@3.0.0`
