### ISSUE TITLE
prod build issue

### ISSUE THREAD

**Issue by Harish-chandra** [ZouYouShun/ngx-hm-carousel#5]
ERROR in : Unexpected value 'NgxHmCarouselModule in /Users/my-app/node_modules/ngx-hm-carousel/ngx-hm-carousel.d.ts' imported by the module 'ExampleModule in /Users/my-app/src/app/modules/example/example.module.ts'. Please add a @NgModule annotation.

**Comment by ZouYouShun** [comment]
Hi @Harish-chandra, I fix it with `1.2.1`, you can try `npm i ngx-hm-carousel@1.2.1` to fix this problem.
