### ISSUE TITLE
#carouselNext and #carouselPrev do not have proper boundary check if infinite is false

### ISSUE THREAD

**Issue by pascalbayer** [ZouYouShun/ngx-hm-carousel#7]
Clicking on #carouselNext and #carouselPrev with infinite=false doesn't have a proper boundary check. You will end up sliding to negative or positive slides that do not exist instead of stopping at the lower/upper limits of the slideIndex.

**Comment by ZouYouShun** [comment]
Hi @pascalbayer , I has fix that problem in 1.2.7, thanks for you correct.
``` npm i ngx-hm-carousel@1.2.7```

You can test it in [Drag One section](https://alanzouhome.firebaseapp.com/package/NgxHmCarousel
).

**Comment by pascalbayer** [comment]
Thanks for the immediate fix, I can confirm it works. 
Great work btw. I haven't found any other carousel implementation that was so easy to use but still allows complex use cases!
