### ISSUE TITLE
Carousel does not recreate <article> containers when changing input binding

### ISSUE THREAD

**Issue by pascalbayer** [ZouYouShun/ngx-hm-carousel#8]
I'm currently facing an issue by binding the carousel slide creation to a dynamic array that contains a changing number of items and image sizes:

```
<article class="image-carousel__item" *ngFor="let image of this.imageMap[activeImageType]">
    <img class="image-carousel__item-image" [src]="image.src" />
</article>
```

Expected behavior would be that the `<article>` elements would be recreated whenever the bound input array changes, however the current behavior doesn't reflect that and doesn't trigger the size calculations or deletion of no longer needed `<article>` elements, leading to unexpected behavior like image overflow over the container bounds, etc.

**Comment by ZouYouShun** [comment]
Hi @pascalbayer , right now binding way is  using `afterViewInit` to set many variable for carousel whirling, if you change the source array length, we must be recalculate those variable again, this maybe cause performance problem.

In my opinion, maybe I can add and rebinding method with carousel, using ngOnChanges is not efficient, and this situation with change carousel is not often in general.

**Comment by pascalbayer** [comment]
@ZouYouShun I agree on your concerns regarding performance by using ngOnChanges. The best way might be to inject a `ngxHmCarouselRef` into the components controller to allow manually triggering the recalculation via e.g. a  `.update()` method.

**Comment by ZouYouShun** [comment]
@pascalbayer I using `QueryList<ElementRef>` to solve this problem, reference 
https://stackoverflow.com/questions/37087864/execute-a-function-when-ngfor-finished-in-angular-2/37088348#37088348

 I publish `ngx-hm-carousel@.2.8` and update the example page whit [add item] button you can check it with https://alanzouhome.firebaseapp.com/package/NgxHmCarousel

**Comment by pascalbayer** [comment]
@ZouYouShun I've updated my local version, however it breaks with the the following error:
```
ERROR TypeError: Cannot read property 'cloneNode' of undefined
    at NgxHmCarouselComponent.push../node_modules/ngx-hm-carousel/fesm5/ngx-hm-carousel.js.NgxHmCarouselComponent.addInfiniteElm (ngx-hm-carousel.js:470)
    at NgxHmCarouselComponent.push../node_modules/ngx-hm-carousel/fesm5/ngx-hm-carousel.js.NgxHmCarouselComponent.init (ngx-hm-carousel.js:398)
    at NgxHmCarouselComponent.push../node_modules/ngx-hm-carousel/fesm5/ngx-hm-carousel.js.NgxHmCarouselComponent.ngAfterViewInit (ngx-hm-carousel.js:373)
    at callProviderLifecycles (core.js:18633)
    at callElementProvidersLifecycles (core.js:18607)
    at callLifecycleHooksChildrenFirst (core.js:18597)
    at checkAndUpdateView (core.js:19533)
    at callViewAction (core.js:19765)
    at execEmbeddedViewsAction (core.js:19728)
    at checkAndUpdateView (core.js:19525)
```
I've debugged it and there are two article elements with content (images) but `this.firstElm_clone = /** @type {?} */ (this.elms[this.lastIndex].cloneNode(true));` -> `this.elms` in `addInfiniteElm()` is an empty array

**Comment by ZouYouShun** [comment]
with 1.2.8 we need QueryList, so add the item directive back, you must add `ngx-hm-carousel-item` to the children item.

```
<ngx-hm-carousel
  (ngModelChange)="change($event)"
  align="left"
  show-num="auto"
  [drag-many]="true"
  class="link-container">
  <section ngx-hm-carousel-container class="content">
    <article class="item cursor-pointer t-al-c"


      ngx-hm-carousel-item



      *ngFor="let item of menus">
      <a [href]="item.url" class="img" target="_blank"
        [style.backgroundImage]="'url('+item.url+')'">
      </a>
    </article>
  </section>
</ngx-hm-carousel>
```

**Comment by pascalbayer** [comment]
Thanks, I can confirm everything is working as expected now.
